vendor: Rafay Systems
name: Rafay
version: v1.6.1
website_url: https://rafay.co/
documentation_url: https://app.rafay.dev/docs/
product_logo_url: https://github.com/rafayopen/k8s-conformance/blob/master/v1.14/Rafay/Rafay_Logo.svg
type: hosted
description: Rafay Systems enables DevOps and SRE teams to automate application lifecycle and cluster configuration management across on-premise and cloud-based Kubernetes clusters through a turnkey SaaS platform.
