vendor: Canonical Ltd
name: MicroK8s
version: v1.14.0
website_url: https://microk8s.io
documentation_url: https://github.com/ubuntu/microk8s/blob/master/README.md
product_logo_url: https://assets.ubuntu.com/v1/9309d097-MicroK8s_SnapStore_icon.svg
type: distribution
description: 'An easy to install, single node local Kubernetes.'
