vendor: Alauda
name: Alauda Cloud Enterprise (ACE)
version: 3.3
website_url: http://www.alauda.cn/product/detail/id/239.html
documentation_url: http://www.alauda.cn/product/detail/id/239.html
product_logo_url: https://landscape.cncf.io/logos/alauda-cloud-enterprise-ace.svg
type: distribution
description: An Enterprise Platform-as-a-Service based on Kubernetes
