vendor: TenxCloud
name: TenxCloud Container Enterprise
version: v1.18.0
website_url: https://www.tenxcloud.com/product/paas.html
documentation_url: http://docs.tenxcloud.com/enterprise
product_logo_url: https://www.tenxcloud.com/img/logo.svg
type: distribution
description: TenxCloud Container Enterprise is a PaaS product based on Kubernetes
