vendor: Portworx
name: Portworx on Kubernetes
version: v1.5
website_url: https://portworx.com/
documentation_url: https://docs.portworx.com/scheduler/kubernetes/
product_logo_url: https://landscape.cncf.io/logos/portworx.svg
type: distribution
description: Cloud Native Storage for Kubernetes
