vendor: Agile Stacks, Inc.
name: Agile Stacks DevOps Automation Platform
version: v1.1.0
website_url: https://www.agilestacks.com
documentation_url: https://docs.agilestacks.com
type: distribution
description: Agile Stacks DevOps automation platform
