vendor: Giant Swarm
name: Managed Kubernetes on KVM
version: 11.3.1
website_url: https://giantswarm.io
repo_url: https://github.com/giantswarm/kvm-operator/
documentation_url: https://docs.giantswarm.io
product_logo_url: https://github.com/giantswarm/happa/blob/v0.10.30/src/images/giantswarm_icon.svg
type: distribution
description: 'The Giant Swarm platform enables users to simply and rapidly create and use 24/7 managed Kubernetes clusters on-demand.'
