vendor: Rancher Inc.
name: RKE - Rancher Kubernetes Engine
version: v0.3.0-rc7
website_url: https://github.com/rancher/rke
documentation_url: https://rancher.com/docs/rke/latest/en/
product_logo_url: https://rancher.com/img/brand-guidelines/assets/logos/png/color/rancher-logo-horiz-color.png
type: Installer
description: Rancher Kubernetes Engine, an extremely simple, lightning fast Kubernetes installer that works everywhere.
