vendor: Red Hat
name: OpenShift Online and OpenShift Container Platform by Red Hat
version: v4.2.0
website_url: https://www.openshift.com
documentation_url: https://docs.openshift.com
product_logo_url: https://cdn2.hubspot.net/hubfs/4305976/images/openshift-legacy/logos/openshift/Logotype_RH_OpenShift_wLogo_RGB_Black.svg
