vendor: BoCloud
name: BoCloud BeyondcentContainer
version: v1.6
website_url: http://bocloud.com.cn/product_container.html
documentation_url: http://bocloud.com.cn/product_container.html
product_logo_url: http://bocloud.com.cn/templates/bocloud/images/logo.png
