vendor: Rancher Labs
name: k3s
version: v1.0.1
website_url: https://k3s.io
documentation_url: https://rancher.com/docs/k3s/latest/en/
product_logo_url: http://k3s.io/img/logo.svg?1
type: distribution
description: Lightweight Kubernetes
