vendor: Agile Stacks, Inc.
name: Agile Stacks DevOps Automation Platform
version: v1.0.2
website_url: https://www.agilestacks.com
documentation_url: https://docs.agilestacks.io
type: distribution
description: Agile Stacks DevOps automation platform
