vendor: IBM
name: IBM Cloud Container Service
version: 1.7.16
website_url: https://www.ibm.com/cloud/container-service
documentation_url: https://console.bluemix.net/docs/containers/container_index.html
product_logo_url: https://raw.githubusercontent.com/ibm-containers/logo/master/iccs.png
