vendor: Amazon Web Services
name: Amazon Elastic Container Service for Kubernetes (Amazon EKS)
version: v1.10.3
website_url: https://aws.amazon.com/eks/
documentation_url: https://docs.aws.amazon.com/eks/latest/userguide/what-is-eks.html
product_logo_url: https://s3-us-west-2.amazonaws.com/amazon-eks-docs/EKS.png
type: platform
description: Amazon Elastic Container Service for Kubernetes (Amazon EKS) is a managed service that makes it easy for you to run Kubernetes on AWS without needing to install and operate your own Kubernetes clusters.
