vendor: Hainan eKing Technology Co., Ltd. 
name: eKing Cloud Container Platform 
version: v1.8.4
website_url: http://www.haihangyun.com/landing
documentation_url: https://help.haihangyun.com/help/#HNAInstruction
product_logo_url: https://www.haihangyun.com/static/dist/logo/cloud_logo.png
