vendor: Giant Swarm
name: Managed Kubernetes on Azure
version: stable-2018-01-05
website_url: https://giantswarm.io
documentation_url: https://docs.giantswarm.io
product_logo_url: https://www.dropbox.com/s/kydb137cjsix7du/giantswarm_ant.png
