vendor: Loodse
name: Kubermatic Container Engine
version: v2.3
website_url: https://loodse.com
documentation_url: https://loodse.com
product_logo_url: https://drive.google.com/file/d/1NdEwTa_Aco_urdyY7bhDjJEPcpyAYRY9
