vendor: VMware
name: VMware Tanzu Kubernetes Grid Integrated Edition
version: v1.0.0
website_url: https://tanzu.vmware.com/kubernetes-grid
documentation_url: https://resources.docs.pivotal.io/pdfs/pks-docs-1.0.pdf
product_logo_url: https://landscape.cncf.io/logos/v-mware-tanzu-kubernetes-grid.svg
