vendor: Huawei
name: HUAWEI CLOUD Cloud Container Engine
version: v1.9.2-CCE2.0.8-B003
website_url: http://www.huaweicloud.com/product/cce.html
documentation_url: http://support.huaweicloud.com/cce/index.html
product_logo_url: http://www.huawei.com/Assets/CBG/img/logo.png
