vendor: Supergiant.io
name: Control
version: 2.1.0
website_url: https://supergiant.io/
documentation_url: https://supergiant.readme.io/docs
product_logo_url: https://camo.githubusercontent.com/c91e8d5eb2a003a8a19d1bfd94df32db9f8cb9e6/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f73757065726769616e742d646f63732d6173736574732f636f6e74726f6c5f6c696768742e737667
type: installer
description: Control manages the lifecycle of clusters on your infrastructure and allows deployment of applications via HELM. Its deployment and configuration workflows will help you to get up and running with Kubernetes faster.
