vendor: Nutanix
name: Karbon
version: v0.8
documentation_url: https://portal.nutanix.com/#/page/docs/details?targetId=Karbon-v08:Karbon-v08
website_url: https://www.nutanix.com
product_logo_url: https://www.nutanix.com/wp-content/uploads/2017/11/nutanix.png
type: hosted
description: Managed Kubernetes offering by Nutanix
