vendor: BoCloud
name: BoCloud BeyondContainer
version: v2.0
website_url: http://bocloud.com.cn/product_container.html
documentation_url: http://bocloud.com.cn/product_container.html
product_logo_url: http://bocloud.com.cn/templates/bocloud/images/logo.png
type: hosted
description: 'BoCloud BeyondContainer is a production-ready PaaS platform for Internet application deployment and management.'
