vendor: SIGHUP
name: kubernetes-fury-aws
version: k8s-1.14.3-fury-1.0.0
website_url: https://github.com/sighupio/fury-kubernetes-aws
repo_url: https://github.com/sighupio/fury-kubernetes-aws
documentation_url: https://github.com/sighupio/fury-kubernetes-aws/blob/master/README.md
product_logo_url: https://s3.us-west-1.wasabisys.com/sighup-logos/fury-logo.svg
type: installer
description: Kubernetes Fury for AWS is a battle-tested distribution purely based on upstream Kubernetes that deploy a production grade Kubernetes Cluster at scale with a comprehensive Cloud Native stack implemented with top notch CNCF components.
