vendor: Microsoft
name: AKS Engine for Azure Stack
version: v0.38.3
website_url: https://github.com/msazurestackworkloads/aks-engine
documentation_url: https://github.com/msazurestackworkloads/aks-engine/blob/master/README.md
product_logo_url: https://landscape.cncf.io/logos/azure-aks-engine.svg