vendor: Woqutech
name: QFusion
version: v3.0.0
website_url: http://www.woqutech.com/product/product-16-247.html#sss
documentation_url: http://www.woqutech.com/product/product-16-247.html#sss
product_logo_url: http://p1sz5a5h3.bkt.clouddn.com/QFusion.svg
