vendor: Woqutech
name: QFusion
version: v3.0.0
website_url: http://woqutech.com/product_qfusion.html
documentation_url: http://woqutech.com/product_qfusion.html
product_logo_url: http://p1sz5a5h3.bkt.clouddn.com/QFusion.svg
