vendor: OVH Group
name: OVH Managed Kubernetes Service
version: beta1
website_url: https://labs.ovh.com/kubernetes-k8s
documentation_url: https://labs.ovh.com/kubernetes-k8s/documentation
product_logo_url: https://www.ovh.com/fr/images/logo/logo-ovh-long-baseline-blue.ai
type: hosted platform
description: 'Benefit from free HA managed Kubernetes service, by hosting your nodes and services on OVH Public Cloud'