vendor: Appscode
name: Pharmer by Appscode
version: 0.1.0-rc.1
website_url: https://appscode.com/products/pharmer
documentation_url: https://appscode.com/products/pharmer/docs
product_logo_url: https://appscode.com/images/logo-color.svg