vendor: Linaro Developer Cloud
name: Linaro Developer Cloud Kubernetes Service
version: v1.17.1
website_url: https://www.linaro.cloud
documentation_url: https://github.com/Linaro/cloud/blob/master/docs/ldc-kubernetes.md
product_logo_url: https://github.com/Linaro/website/blob/develop/assets/images/content/Linaro-Logo.svg
repo_url: https://github.com/Linaro/magnum
type: hosted
description: Linaro Developer Cloud Kubernetes service make it easy for you to deploy, manage, and scale Kubernetes clusters to run containerised applications on the Arm64 platform.

