vendor: Docker
name: Docker Enterprise Edition
version: TBD
website_url: https://www.docker.com/enterprise-edition
documentation_url: https://docs.docker.com/enterprise/
product_logo_url: https://www.docker.com/sites/default/files/vertical_large.png
