vendor: Supergiant
name: Supergiant
version: 1.1.0
website_url: https://supergiant.io/
documentation_url: https://supergiant.readthedocs.io/en/v1.0.0/
product_logo_url: https://github.com/supergiant/supergiant/blob/master/cmd/ui/assets/src/assets/img/supergiant.svg
type: distribution
description: Supergiant is a flexible Kubernetes toolkit for empowering developers, administrators, and beginners.