vendor: DaoCloud
name: DaoCloud Enterprise
version: v1.15.3
website_url: https://www.daocloud.io/dce
documentation_url: https://download.daocloud.io/DaoCloud_Enterprise/DaoCloud_Enterprise/3.1.4
product_logo_url: https://guide.daocloud.io/download/attachments/524290/global.logo?version=2&modificationDate=1469173304363&api=v2
