vendor: Mirantis
name: Mirantis Cloud Platform
version: v1.10.3-3+93532daa6d674c
website_url: https://www.mirantis.com/software/kubernetes/
documentation_url: https://docs.mirantis.com/mcp/latest/
product_logo_url: https://www.mirantis.com/wp-content/uploads/2017/11/mirantis-logo-2color-rgb-tagline.png
