vendor: Canonical Ltd
name: Charmed Distribution of Kubernetes
version: v1.8.1
website_url: https://www.ubuntu.com/kubernetes
documentation_url: https://kubernetes.io/docs/getting-started-guides/ubuntu/
product_logo_url: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.svg
