vendor: Wise2C
name: WiseCloud
version: v1.7.3
website_url: http://www.wise2c.com/solution
documentation_url: http://www.wise2c.com/Assets/WiseCloud/doc/WiseCloud_User_Guide.pdf
product_logo_url: http://www.wise2c.com/Assets/WiseCloud/img/WiseCloud.png
