vendor: Google
name: Google Container Engine
version: v1.7.8
website_url: https://cloud.google.com/container-engine/
documentation_url: https://cloud.google.com/container-engine/docs/
product_logo_url: https://cloud.google.com/_static/97fb761314/images/cloud/gcp-logo.svg
