vendor: StackPointCloud
name: StackPointCloud
version: v1.0
website_url: https://stackpoint.io
documentation_url: https://stackpoint.io
product_logo_url: https://github.com/StackPointCloud/spc-community/blob/master/app/assets/stackpointcloud.png
