vendor: Giant Swarm
name: Managed Kubernetes on KVM
version: stable-2017-11-22
website_url: https://giantswarm.io
documentation_url: https://docs.giantswarm.io
product_logo_url: https://www.dropbox.com/s/kydb137cjsix7du/giantswarm_ant.png
