vendor: Inspur
name: Board
version: v1.15.3
website_url: https://github.com/inspursoft/board
repo_url: https://github.com/inspursoft/board
documentation_url: https://github.com/inspursoft/board/tree/master/docs
product_logo_url: https://github.com/inspursoft/board/blob/master/docs/img/board_logo.svg
type: distribution
description: The Board product is a container service platform based on docker + kubernetes.