vendor: Docker
name: Docker Desktop for Mac
version: 2.3.1.0
website_url: https://hub.docker.com/editions/community/docker-ce-desktop-mac
documentation_url: https://docs.docker.com/docker-for-mac/
product_logo_url: https://www.docker.com/sites/default/files/vertical_large.png
type: distribution
description: Docker Desktop for Mac is an easy-to-install desktop app for building, debugging and testing Dockerized apps on a Mac.