vendor: Microsoft
name: Azure acs-egine
version: v0.23.0
website_url: https://github.com/Azure/acs-engine
documentation_url: https://github.com/Azure/acs-engine
product_logo_url: https://i1.wp.com/buildazure.com/wp-content/uploads/2017/09/Azure.png
