vendor: Kubernetes Kops Project
name: kops
version: 1.18.0-beta.1
website_url: https://kops.sigs.k8s.io
documentation_url: https://github.com/kubernetes/kops
product_logo_url: https://raw.githubusercontent.com/kubernetes/kops/master/docs/img/logo.svg
type: installer
description: 'kops is open-source, community-maintained tooling for production-grade kubernetes cluster installation, management and upgrades'
