vendor: CoreOS
name: Tectonic
version: 1.9.6-tectonic.1
website_url: https://coreos.com/tectonic/
documentation_url: https://coreos.com/tectonic/docs/latest/
product_logo_url: https://coreos.com/assets/images/brand/tectonic-bycoreos-color.png
