vendor: Loodse
name: Kubermatic Container Engine
version: v2.0
website_url: https://loodse.io
documentation_url: https://loodse.io
product_logo_url: https://drive.google.com/file/d/1NdEwTa_Aco_urdyY7bhDjJEPcpyAYRY9
