vendor: Harmonycloud
name: Harmonycloud Container Platform
version: v1.9.0
website_url: http://harmonycloud.cn/products/rongqiyun/
documentation_url: http://harmonycloud.cn/products/rongqiyun/
product_logo_url: http://harmonycloud.cn/wp-content/themes/harmonycloud/assets/images/logo.png