vendor: Fairwinds Ops
name: ClusterOps
version: 1.15.7
website_url: https://www.fairwinds.com
documentation_url: https://www.fairwinds.com/clusterops
product_logo_url: https://www.fairwinds.com/hubfs/FW-Logo-Warm-Navy.svg
type: hosted
description: Managed Kubernetes platform hosted on AWS/GCP/AZURE
