vendor: SAP
name: Cloud Platform - Gardener (https://github.com/gardener/gardener) shoot cluster deployed on Microsoft Azure
version: 0.1.0 (changed with Open Source shipment)
website_url: https://cloudplatform.sap.com/index.html
documentation_url: https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/
product_logo_url: https://www.sap.com/dam/application/shared/logos/sap-logo-svg.svg
