vendor: SUSE
name: SUSE CaaS (Container as a Service) Platform
version: v2.0
website_url: https://www.suse.com/products/caas-platform/
documentation_url: https://www.suse.com/betaprogram/caasp-beta/doc-quickstart/
product_logo_url: https://www.suse.com/brandcentral/img/suse/logo-primary.png
