vendor: Huawei
name: HUAWEI FusionStage
version: v1.9.2-FusionStage2.3
website_url: http://developer.huawei.com/ict/en/site-paas
documentation_url: http://developer.huawei.com/ict/cn/rescenter/CMDA_FIELD_FUSION_STAGE?developlan=Other
product_logo_url: http://www.huawei.com/Assets/CBG/img/logo.png
