vendor: Oracle
name: Oracle Cloud Infrastructure Container Engine For Kubernetes
version: 1.3.10
website_url: https://cloud.oracle.com/containers/kubernetes-engine
documentation_url: https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengoverview.htm
product_logo_url: https://www.oracle.com/webfolder/s/brand/identity/logo/index.html#primary
type: hosted platform
description: Oracle Managed Kubernetes