vendor: JD.COM
name: Jingdong Datacenter OS
version: v1.10.2
website_url: http://tig.jd.com/en/products/jdos
type: distribution
documentation_url: http://tig.jd.com/docs/jdos
product_logo_url: http://storage.360buyimg.com/cncf/jdtig.ai

