vendor: Kingsoft Cloud
name: Kingsoft Container Engine
version: v1.17.6
website_url: https://www.ksyun.com/post/product/KCE
documentation_url: https://docs.ksyun.com/products/46
product_logo_url: https://www.cncf.io/wp-content/uploads/2019/03/kingsoft.svg
type: hosted
description: 'Kingsoft Container Engine (KCE) is a container management service with high scalability and high performance.'
