vendor: Mesosphere
name: Mesosphere Kubernetes Engine
version: 2.5.0-1.16.9
website_url: https://mesosphere.com/product/kubernetes-engine/
documentation_url: https://docs.mesosphere.com/services/kubernetes/2.5.0-1.16.9/
product_logo_url: https://user-images.brand.ai/mesosphere/mesosphere-brand-guidelines/mesosphere--vertical--color--dark-rkNdNBK83M.svg
type: distribution
description: 'Mesosphere Kubernetes Engine makes it easy to deploy and manage Kubernetes on DC/OS.'