vendor: Robin Systems Inc   

name: hyper-converged-kubernetes, robin

version: v1.11

website_url: https://robinsystems.com/product/hyper-converged-kubernetes/

documentation_url: https://robinsystems.com/product/hyper-converged-kubernetes/

product_logo_url: https://robinsystems.com/wp-content/uploads/2018/08/robin-systems-logo-180x100.png
