vendor: inwinSTACK
name: kube-ansible
version: v1.13.0
website_url: https://www.inwinstack.com/en/products/?tab=tLink_5
documentation_url: https://github.com/inwinstack/kube-ansible
product_logo_url: http://www.inwinstack.com/wp-content/uploads/2017/09/%E8%B3%87%E7%94%A2-3@0.5x.png