vendor: Netease
name: Netease Container Service Dedicated
version: v1.1
website_url: https://www.163yun.com/product/container-service-dedicated
documentation_url: https://www.163yun.com/docs/product/container-service-dedicated/introduction
product_logo_url: https://www.163yun.com/res/3rd/ndk.png
