vendor: Platform9 Systems, Inc.
name: Platform9 Managed Kubernetes
version: v3.3
website_url: https://platform9.com/managed-kubernetes/
documentation_url: https://platform9.com/support/
product_logo_url: https://platform9.com/wp-content/themes/p9/bld/img/logo/logo.svg
