vendor: Weaveworks
name: kubeadm
version: v1.10.0
website_url: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
documentation_url: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
product_logo_url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg
