vendor: SUSE
name: SUSE CaaS (Container as a Service) Platform
version: v4.2
website_url: https://www.suse.com/products/caas-platform/
documentation_url: https://documentation.suse.com/suse-caasp/4.2/
product_logo_url: https://links.imagerelay.com/cdn/3404/ql/7fd3b38461a44838a6a1621f1fbf0daa/Program-Marks.zip
repo_url: https://github.com/SUSE/skuba
type: distribution
description: SUSE CaaS (Container as a Service) Platform is an application development and hosting platform for container applications and services that enables you to provision, manage, and scale container-based applications and services.

