vendor: Huawei
name: HUAWEI FusionStage
version: v1.13.4-FusionStage8.0-B001
website_url: http://developer.huawei.com/ict/cn/site-paas
documentation_url: http://developer.huawei.com/ict/cn/rescenter/CMDA_FIELD_FUSION_STAGE?developlan=Other
product_logo_url: http://www.huawei.com/Assets/CBG/img/logo.png
