vendor: ZTE
name: TECS OpenPalette
version: v1.18.10
website_url: https://sdnfv.zte.com.cn/zh-CN/home
documentation_url: https://sdnfv.zte.com.cn/zh-CN/products/125
product_logo_url: https://sdnfv.zte.com.cn/upload_files/93a82082-e075-11e7-8fe0-744aa40210b9.jpg
