vendor: SUSE
name: SUSE CaaS (Container as a Service) Platform
version: v3.0
website_url: https://www.suse.com/betaprogram/caasp-beta/
documentation_url: https://www.suse.com/betaprogram/caasp-beta/#documentation
product_logo_url: https://www.suse.com/brandcentral/img/suse/logo-primary.png
