vendor: Exon LV
name: Kubernetes Distribution by Containerum
version: v 1.11.3
website_url: https://containerum.com
documentation_url: https://docs.kdc.containerum.com
product_logo_url: https://containerum.com/img/logo_kdc.svg
type: distribution
description: 'Production-ready distribution of Kubernetes, tested and maintained by Containerum engineers.'
