vendor: VMware
name: VMware Tanzu Kubernetes Grid Integrated Edition
version: v0.1.0
website_url: https://tanzu.vmware.com/kubernetes-grid
documentation_url: https://docs-pks.cfapps.io/pks/index.html
product_logo_url: https://landscape.cncf.io/logos/v-mware-tanzu-kubernetes-grid.svg
