vendor: Bluemeric Technologies Private Limited
name: gopaddle
version: v1.3.0
website_url: https://gopaddle.io
documentation_url: http://docs.gopaddle.io/docs/
product_logo_url: https://gopaddle.io/images/b8f3f545.logo_black1.png
