vendor: Samsung SDS
name: Kraken
version: v1.2.1
website_url: https://github.com/samsung-cnct/kraken
documentation_url: https://github.com/samsung-cnct/kraken
product_logo_url: https://github.com/samsung-cnct/kraken-lib/blob/master/sphinx/_static/kraken.png