vendor: Kublr
name: Kublr
version: v1.10.0
website_url: https://kublr.com
documentation_url: https://docs.kublr.com
product_logo_url: https://kublr.com/wp-content/themes/kublr-2018-theme/images/logo/kublr-logo.svg
