vendor: Alibaba Cloud
name: Alibaba Cloud Container Service
version: v1.9.3
website_url: https://www.aliyun.com/product/containerservice?spm=5176.8142029.388261.219.3836dbccRpJ5e9
documentation_url: https://help.aliyun.com/document_detail/53751.html?spm=5176.product25972.6.807.xyL0pU
product_logo_url: https://avatars2.githubusercontent.com/u/16377432?s=200&v=4