vendor: SUSE
name: SUSE CaaS (Container as a Service) Platform
version: v4.0
website_url: http://beta.suse.com/private/SUSE-CaaSP-Beta/
documentation_url: https://susedoc.github.io/#caasp 
product_logo_url: https://www.suse.com/brandcentral/img/suse/logo-primary.png
type: distribution
description: SUSE CaaS (Container as a Service) Platform is an application development and hosting platform for container applications and services that enables you to provision, manage, and scale container-based applications and services.
