vendor: Kontena
name: Kontena Pharos
version: v1.1.0-rc.3
website_url: https://kontena.io/pharos/
documentation_url: https://www.pharos.sh/docs/
product_logo_url: https://pharos.sh/images/logo-blue.png
type: distribution
description: Kontena Pharos - The simple, solid, certified Kubernetes distribution that just works.