vendor: DaoCloud
name: DaoCloud Enterprise
version: v1.9.6
website_url: http://www.daocloud.io/dce
documentation_url: http://guide.daocloud.io/dce-v3.0
product_logo_url: http://guide.daocloud.io/download/attachments/524290/global.logo?version=2&modificationDate=1469173304363&api=v2
