vendor: Twistlock Ltd
name: Twistlock
version: v2.2.100
website_url: https://www.twistlock.com/
documentation_url: https://www.twistlock.com/platform/
product_logo_url: http://www.twistlock.com/wp-content/uploads/2017/11/Twistlock_Logo-Lockup_RGB.png

