vendor: Platform9 Systems, Inc.
name: Platform9 Managed Kubernetes
version: v3.5
website_url: https://platform9.com/managed-kubernetes/
documentation_url: https://platform9.com/support/
product_logo_url: https://platform9.com/wp-content/uploads/2018/02/Platform9-logo-cnfc.png
