vendor: Nutanix
name: Karbon
version: v2.0.1
documentation_url: https://portal.nutanix.com/page/documents/details/?targetId=Release-Notes-Karbon-v2_0_1%3ARelease-Notes-Karbon-v2_0_1
website_url: https://www.nutanix.com
product_logo_url: https://www.nutanix.com/wp-content/uploads/2017/11/nutanix.png
type: hosted
description: Managed Kubernetes offering by Nutanix
