vendor: Mesosphere
name: Kubernetes on DC/OS
version: 0.4.0-1.9.0-beta
website_url: https://mesosphere.com/kubernetes/
documentation_url: https://docs.mesosphere.com/services/beta-kubernetes/0.4.0-1.9.0-beta/
product_logo_url: https://mesosphere.com/wp-content/uploads/2017/11/MESO_dcos_Horz_RGB-SJxDvlwp3-.png 
