vendor: Univa 
name: Navops Command
version: 1.3.3
website_url: https://navops.io/command.html
documentation_url: https://storage.googleapis.com/navops/doc/latest/command.html
product_logo_url: https://www.navops.io/img/command-logo-color.png
