vendor: Kinvolk GmbH
name: kube-spawn
version: v0.3.0
website_url: https://github.com/kinvolk/kube-spawn
documentation_url: https://github.com/kinvolk/kube-spawn
product_logo_url: https://raw.githubusercontent.com/kinvolk/kube-spawn/master/logos/PNG/kube_spawn-horz_prpblkonwht.png
