vendor: Weaveworks
name: Weave Kubernetes Platform
version: 2.0.3
website_url: https://www.weave.works/product/enterprise-kubernetes-platform/
documentation_url: https://www.weave.works/weave-kubernetes-platform-how-to-guide/
type: distribution
description: A complete Kubernetes platform that combines pure upstream open source Kubernetes from a curated set of platform components with GitOps.
