vendor: Alauda
name: Alauda EE
version: v1.10.0
website_url: http://www.alauda.cn/product/detail/id/68.html
documentation_url: http://developer.alauda.cn/usermanual/features/clusterkubernetes.html
product_logo_url: https://enterprise.alauda.cn/static/images/logo/logo-login-large.svg
