vendor: Kontena
name: Kontena Pharos
version: v0.4.0
website_url: https://pharos.sh
documentation_url: https://github.com/kontena/pharos-cluster/blob/master/README.md
product_logo_url: https://pharos.sh/images/logo-blue.png
type: distribution
description: Kontena Pharos - The simple, solid, certified Kubernetes distribution that just works.