vendor: Diamanti Inc.
name: Diamanti-D10
version: 2.1.0
website_url: https://diamanti.com/products
documentation_url: https://support.diamanti.com
product_logo_url: https://diamanti.com/wp-content/uploads/2018/07/Diamanti-Logo-Stacked.jpg
description: 'Diamanti D10 Bare-Metal Container Platform based on Kubernetes.'
