vendor: Rackspace
name: Rackspace Kubernetes-as-a-Service
version: 1.1.0
website_url: https://www.rackspace.com/managed-kubernetes
documentation_url: https://developer.rackspace.com/docs/rkaas/1.0.x/
product_logo_url: http://blog.rackspace.com/wp-content/uploads/2016/03/rs-logo-lg-use-rgb.jpg