vendor: Apprenda
name: Kismatic Enterprise Toolkit (KET)
version: v1.6.0
website_url: https://apprenda.com/kismatic/
documentation_url: https://github.com/apprenda/kismatic/tree/v1.6.0/docs
product_logo_url: https://raw.githubusercontent.com/apprenda/kismatic/v1.6.0/docs/logo/KET_logo.png