vendor: Agile Stacks, Inc.
name: Agile Stacks DevOps Automation Platform
version: v1.0.1
website_url: https://www.agilestacks.com
documentation_url: https://docs.agilestacks.io
product_logo_url: https://cdn2.hubspot.net/hubfs/2850695/Agile_Stacks_LogoT.png
type: distribution
description: Agile Stacks DevOps automation platform
