vendor: eBaoTech
name: eBaoCloud Platform
version: v1.0.0
website_url: https://sg.ebaocloud.com/
documentation_url: https://sg.ebaocloud.com/
type: distribution
product_logo_url: https://enablement.ebaocloud.com/staticfile/img/ebaocloud.svg
