vendor: Kontena
name: Kontena Pharos
version: v2.1.0-rc.2
website_url: https://kontena.io/pharos/
documentation_url: https://www.pharos.sh/docs/
product_logo_url: https://kontena.io/images/kontena-logo-solid-horizontal.svg
type: distribution
description: Kontena Pharos - The simple, solid, certified Kubernetes distribution that just works.