vendor: Joyent
name: Triton Kubernetes
version: v0.9.1
website_url: https://github.com/joyent/triton-kubernetes
repo_url: https://github.com/joyent/triton-kubernetes
documentation_url: https://github.com/joyent/triton-kubernetes/blob/master/README.md
product_logo_url: https://www.joyent.com/assets/products/joyent-kubernetes-(1)-1579210373.svg
type: distribution
description: Triton Kubernetes is a multi-cloud Kubernetes solution. It has a global cluster manager (control plane) which can run and manage Kubernetes environments on any cloud - Public, Private or Bare Metal.