vendor: Mirantis
name: Mirantis Docker Enterprise
version: 3.1
website_url: https://www.mirantis.com/software/docker/docker-enterprise/
documentation_url: https://docs.docker.com/enterprise/
product_logo_url: https://www.mirantis.com/json/mirantis-logo.svg
type: distribution
description: Mirantis Docker Enterprise includes Universal Control Plane (UCP) with built-in certified Kubernetes distribution.
