vendor: Oracle
name: Oracle Linux Cloud Native Environment
version: 1.1.0
website_url: https://www.oracle.com/linux/cloudnative/
documentation_url: https://docs.oracle.com/en/operating-systems/olcne/
product_logo_url: https://opensource.oracle.com/docs/Oracle-Linux-Logo.svg
type: distribution
description: 'Oracle Linux Cloud Native Environment is a fully integrated suite for the development and management of cloud-native applications that uses Kubernetes to orchestrate and schedule containers.'
