vendor: Diamanti
name: Diamanti-D10
version: 1.2.1
website_url: https://diamanti.com/products
documentation_url: https://support.diamanti.com
product_logo_url: https://drive.google.com/file/d/1wjz7K4klrC4B9_rZvEc_NuIRfPUNyyZZ/view?usp=sharing
