vendor: SamsungSDS
name: SamsungSDS Kubernetes Service
version: v1.17
website_url: https://cloud.samsungsds.com/
product_logo_url: https://github.com/thdrnsdk/SamsungSDS-Kubernetes-Service/blob/master/logo.jpg
type: hosted
description: `SamsungSDS Kubernetes Service is a Kubernetes Service on Private Cloud provied SamsungSDS`