vendor: Wind River Systems
name: Wind River Cloud Platform
version: 19.12
website_url: https://www.windriver.com/products/cloud-platform/
repo_url: https://github.com/wind-river/starlingx-config
documentation_url: https://docs.starlingx.io
product_logo_url: https://www.windriver.com/products/cloud-platform/images/cp-video-cover.jpg
type: distribution
description: 'Wind River Cloud Platform is a production-grade Kubernetes solution that makes 5G possible by solving the operational problem of deploying and managing distributed edge networks at scale.  It is Wind River's commercial product based on the open source StarlingX project.'
