vendor: Mirantis
name: Mirantis Cloud Platform
version: v1.8.4-3+ee722cc687e055
website_url: https://www.mirantis.com/software/kubernetes/
documentation_url: https://docs.mirantis.com/mcp/latest/
product_logo_url: https://www.mirantis.com/wp-content/uploads/2017/11/mirantis-logo-2color-rgb-tagline.png
