vendor: Google
name: Google Kubernetes Engine
version: v1.8.0
website_url: https://cloud.google.com/kubernetes-engine/
documentation_url: https://cloud.google.com/kubernetes-engine/docs/
product_logo_url: https://cloud.google.com/_static/97fb761314/images/cloud/gcp-logo.svg
