vendor: Darx Kies
name: Kubernetes - The Easier Way
version: v1.10.4
website_url: https://github.com/darxkies/k8s-tew
documentation_url: https://github.com/darxkies/k8s-tew
product_logo_url: https://raw.githubusercontent.com/darxkies/k8s-tew/master/logo.svg
