vendor: Weaveworks
name: kubeadm
version: v1.14.2
website_url: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
repo_url: https://github.com/kubernetes/kubeadm/
documentation_url: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
product_logo_url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg
type: installer
description: kubeadm helps you bootstrap a minimum viable Kubernetes cluster that conforms to best practices.