vendor: Intellect Design Arena Inc
name: Intellect FABRIC
version: v19.1.0
website_url: https://www.intellectseec.com/
documentation_url: https://www.intellectseec.com/insurtech-platform
product_logo_url: https://github.com/intellectdesign/intellectseeclogo/blob/master/IntellectSEEC_Logo.svg
type: Hosted platform
description: Intellect FABRIC, an InsurTech Machine Learning Platform, help insurers improve profitability and enhances customer experience with Cloud Native products. Intellect FABRIC offers Distribution Services Suite for complete digital transformation; Life Claims providing Claims Processing for LAH Insurers; and Risk Analyst and Xponent providing AI powered underwriting solution for commercial lines.
