vendor: Giant Swarm
name: Managed Kubernetes on KVM
version: 9.0.0
website_url: https://giantswarm.io
repo_url: https://github.com/giantswarm/kvm-operator/
documentation_url: https://docs.giantswarm.io
product_logo_url: https://www.dropbox.com/s/kydb137cjsix7du/giantswarm_ant.png
type: distribution
description: 'The Giant Swarm platform enables users to simply and rapidly create and use 24/7 managed Kubernetes clusters on-demand.'
