vendor: Huawei
name: HUAWEI FusionStage
version: v1.15.0-FusionStage8.0-B040
website_url: https://www.huaweicloud.com/solution/fusionstage
documentation_url: https://support.huawei.com/enterprise/en/cloud-computing/fusionstage-pid-21733180
product_logo_url: http://www.huawei.com/Assets/CBG/img/logo.png
