vendor: Mirantis
name: Mirantis Cloud Platform
version: v1.12.4-3+680746c29c3258
website_url: https://www.mirantis.com/software/kubernetes/
documentation_url: https://docs.mirantis.com/mcp/q4-18/
product_logo_url: https://www.mirantis.com/wp-content/uploads/2017/11/mirantis-logo-2color-rgb-tagline.png
