vendor: Appscode
name: Pharmer by Appscode
version: TBD
website_url: https://appscode.com/products/pharmer
documentation_url: https://appscode.com/products/pharmer/docs
product_logo_url: https://appscode.com/images/logo-color.svg