vendor: Hangzhou FIT2CLOUD Information Technology Co., Ltd.
name: KubeOperator
version: v2.6.18
website_url: https://www.kubeoperator.io/
repo_url: https://github.com/KubeOperator/KubeOperator
documentation_url: https://docs.kubeoperator.io/
product_logo_url: https://raw.githubusercontent.com/KubeOperator/KubeOperator/master/kubeoperator-logo.svg?sanitize=true
type: Installer
description: KubeOperator is an open source project that deploys and manages production-level Kubernetes clusters on VMware, Openstack, or physical machines using a visual Web UI in an offline network environment.
