vendor: Google
name: Google Kubernetes Engine
version: 1.15.9-gke.8
website_url: https://cloud.google.com/kubernetes-engine/
documentation_url: https://cloud.google.com/kubernetes-engine/docs/
product_logo_url: https://www.gstatic.com/devrel-devsite/prod/ve2ae1395f351e38dc0b3037132204261d76b8f1c638764d7fd2c2fbb865782fc/cloud/images/cloud-logo.svg
type: hosted
description: 'GKE is an enterprise-grade platform for containerized applications, including stateful and stateless, AI and ML, Linux and Windows, complex and simple web apps, API, and backend services.'
