vendor: Inspur
name: ICKS
version: v2.1
website_url: http://www.inspur.com/lcjtww/2315499/2315503/2315599/2318015/2471349/index.html
documentation_url: http://www.inspur.com/lcjtww/2315499/2315503/2315599/2318015/2471349/2019072215054965674.pdf
product_logo_url: https://upload.wikimedia.org/wikipedia/en/7/73/Inspur_logo.svg
type: hosted 
description: ICKS, offering full lifecycle management services, is an application-centric platform which provides a High-available managed environment to simplify the development, CI/CD, deployment, scheduling and scaling of containerized applications. 
